version: '3'
services:
    postgres:
        image: postgres:10
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=odoo
            - POSTGRES_PASSWORD=odoo
            - PGDATA=/var/lib/postgresql/data/pgdata
        volumes:
            - odoo-db-data:/var/lib/postgresql/data/pgdata
    odoo:
        build: .
        depends_on:
            - postgres
        ports:
            - "8069:8069"
        volumes:
            - odoo-web-data:/var/lib/odoo
            - ./config:/etc/odoo
            - ./addons:/mnt/extra-addons
volumes:
    odoo-web-data:
    odoo-db-data: